<!--
    Group Name		: FIVE
    Group Number	: 5
    
    Author			: Pattarapol Tantechasa		Student ID:	103883220
    Author			: Sam Anderson 				Student ID:	104465030
    Author			: Ngoc Huy Duong			Student ID:	104471956

-->

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="description" content="Five Technology Website" />
    <meta name="keywords" content="Jobs Vacancies" />
    <meta name="author" content="FIVE" />
    <link rel="stylesheet" href="./styles/style.css" />
  </head>
</html>
